sudo: false
language: python
matrix:
  include:
    - python: "3.5"
before_install:
  - "pip install 'lander>=0.1.0,<0.2'"
script:
  # Compile PDF using containerized lsst-texmf
  - "docker run --rm -v `pwd`:/workspace -w /workspace lsstsqre/lsst-texmf:latest sh -c 'make'"
  # Deploy website. See https://github.com/lsst-sqre/lander for CLI options
  - "lander --pdf DMTN-072.pdf --upload --lsstdoc DMTN-072.tex --env=travis --ltd-product dmtn-072"
env:
    # Add AWS and LTD Keeper credentials as encrypted secrets here
    - secure: "A0Nu7Ckd0gZrs9AOMWs4OScVLp9PkdNHTopL6qwrGA1klhWlJwgXa2NxEtEglBPWR9f3lS+Pgqea2aX/fZbfU7bJD2EJ9GsqAZEyK4mBOqp356sS3DrtPuTRRCL+Uzkdc8VDIra+CXkzEsRGansRbFZcSeaEdER36t69Rg4E7/DbJBb0f7oqmprNc3lYe1M2zvVOdyJb1rQ3t++SsiXvQlICari+IQNsZwiUVONatDlpUU33l+v3uww4UD/qmHzVmajM0NBbC/Q14IyzTVX/RH0K/yCJ43/ErHxGpKzHk5lY4lEgMZdXIJkhtxHaYbQ5wRNdAaKBWnqtQHbYb1A0FeU7Zr2WHqyvH04vOluJT1l9wDo+Ek34ODX23SVKeg5tAOceEUL/gy+Qxss5grQ3i3uYaI1AY1fjwJKph4rhVjFPHNPBoHsjYeYV0+wOnyvIcRAcs+8JJMEV/QeQlpRSFCxhF3XAiz5SoGd8qMVNu6dc30fe7aaAl+eZvo7kmkKAAxn7i5l6ML9Ax7paBPIVuKd+au95jcva65vNRD4t3gaMWcdxaYr5XnVd9Pls2BAavTsD+hResB3o1Oe/VtEXlbknJs6Djfd3qBNNt6pXmhsPZM4l2kq7IYags+avj6J4yL9+Z2HInu28bRlOABrvv+V0Fh36to6zbDdysUoypyo="
    - secure: "JS2BTkuExl4YFSo4qIIlyUNFI09hnQD41QBd4ytkxUc2Eh3Hp5Q/Nm3/nxEkVNF29mrKGD+oWpgrRosCSmOPWTVJ0RwVarafjYDE9HmJi4IcdRu1LHNt1Ie80b2lwIrxvk2D6WSD284RNWaNC+BmyyXHw+0jC9l3mm47Unps+P2fEfUS7hz/DUjuKo8C/BblpSATnCAWofiilkohKwMbs2oqHMIA9OeidI2MHiZLH6d5r3xMjC1DFAn/J9hbv7E0HzNlxvuh8sgM05ceFxqeaGLdrQaGqqlS+lw+AzNrNbWf7+WkeqFxsL4zxl8nqDZzd+cWn0P9D3Pj3k+9v+iTXsHdWBc2xEz+NnMdFdcoyKRmQPEhIqGZ+zoBLIeLLhCZU9hBpa6K/9yitTzagckHXfqUKH3FgMNSyZP3UU78MjBAfiGhie6KmYaoxyBpOn9orL4XR9Y7kylZkuor5MLPeuLpCgyih5bIaAkbq7enD4a+Hxm7BPxSZ2rkoQxHceR2EJIjnGHMKDn5WSJ03Pop0hT5XgmvqGpYejz4JWaU2W0+2eRrBZjNBUlkBH8kbxu2cFHKEUpylHOodYmCZShzGiLDUTLeCoAyjFnsKOhTpICzCa9g7KskIzXwq2JXx+7PFXeamfAfRcrNtkzhgwVGzwlAMX8Kd39fGyn+Pd7Krrw="
