sudo: false
language: python
matrix:
  include:
    - python: "3.5"
before_install:
  - "pip install 'lander>=0.1.0,<0.2'"
script:
  # Compile PDF using containerized lsst-texmf
  - "docker run --rm -v `pwd`:/workspace -w /workspace lsstsqre/lsst-texmf:latest sh -c 'make'"
  # Deploy website. See https://github.com/lsst-sqre/lander for CLI options
  - "lander --pdf DMTN-072.pdf --upload --lsstdoc DMTN-072.tex --env=travis --ltd-product dmtn-072"
env:
  global:
    - secure: "lnR0ldMn8ZoRoFIeQVPU7Gx9/TS8ESNYTIVUh2l3zZAIv73AxQMwHAbFXfaVavAQl+eN9b/Rh22qytcD/PO9hhY4uQqIRChlJfeK6QMtA7xXixDAvbHDzU9i74IvLesxmFHWl5jqvBBkBhht9Ddjpp+RU98vGtJbExuE/0nJyE3GV4UmmICBby2iJNX40kPsKdvpoougeMnDxWnsZFj/TJO+0CYpvmMSVCTHc3AVW/CzrSgu4l6wwmSKBKFOtrbpTSLcVB7aoON1AP021RHBOQsnpfE8CMQx3T3CIsSOAIMqS8REf6o72JIVJmX4CHNN2asO7GBrfZWZlv/9tdAEKlUoHakOHAdOu3ywHosQiZUzbeXKDm9IT9pjvkb8UMTIK0bwu4NwxowYF7LrBIo0GxUK7Bp9ZA1HMEtvtTN/QTB9wZ9PvRPtaRhsumgslDZQOCqJISHDlT0NwOefDaYCvVcufIOEAt7zzJiOF6XRqnTuu4TXM66i11SUl4poHWCGIaeRcc4OKS2Rjiw2B8iOlh/p/AIh7Nji+6prQchb/a9F4foiwy+KkgFxuNqfj7fJdIyma4z4qYp1Zv2JrJgmn5e1Wx0K3gaQUdWvhtKXcC/ypuodGsQKTitd4XIqZNqDrT+RBDW6XhlTs84sDJm1CxyScaBkHvJp+XmWetzNqc0="
    - secure: "RKRr3SUS/q6NZO/4F+nbiNiXvWry8tzbd7kpa20dK8EODA+4VNpZvTzlSR/ApI1WQn+g8KN7yWnm9pwy/lIj5g4B/gxZTydfbGDV0tz/2/UnxlVRlq2nyeiWCZ7IXOHyplCdWxi0IT0+d2wntz1Oe0l86z/gYgZciPNXOmwW2aDP5fcC0DrKI3QEzpJwWWtTMNKd501gzD0s04mNpcqSZ5T4sgbJcqeKO3L3v/p+Yk0VSKoBYq+fazQy6JCMYVf2FdXkdR0z05WNea01N+k/ulFSelioV28Z4w4BnynOUJzgC1NaQ5TI550d6Dq5YQUx2P828yPjW47MoovnrGJS6zIdYaDHoUiLzOS0KhmypRGENzlfzwQ9F2r1Nj9AV0HRu2oFyOIKIcFLUxqivnkRMQ+58rUOXG/GV6skJXC0J5qg//MZd/s4HY9JZMzLgnhEkhqrjnHHeiG1cDPx/lqEBgz9dijODtTkAU+gzOaW525lqzi7oUjOSugV+TZ8oRoGBe2nnMKpGYYM6TF0rLYLYnmz+W0U9z60cgN0FPlJ3z7Fv38qmNh70YQPf2QnIr2RGgtjFWL27ndhG32yhBqfg8OEA0VUrv22yrCZtEDdSKsyOTQGOvXsuIWaxe/jyh1crSRg2WHgPg1tz1MqOQkyQV5zHNIQcYYj1krTqmF8kvg="
